spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: Corsi
          uri: http://localhost:8081
          predicates:
            - Path=/corsi/**
        - id: Discenti
          uri: http://localhost:8080
          predicates:
            - Path=/discenti/**
        - id: Docenti
          uri: http://localhost:8080
          predicates:
            - Path=/docenti/**

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/corso
    username: postgres
    password: 1234567890
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  port: 9090

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    root: INFO

jwt:
  secret-key: myVeryLongSecretKeyThatIsAtLeast32Characters!
  expiration: 86400
